name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-app:
    name: BuildApp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 16
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build
        env:
          CI: true
      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: out
          path: ./out/

  build-functions:
    name: BuildFunctions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 16
      - name: npm install, build, and test
        working-directory: ./functions
        run: |
          npm ci
          npm run build
        env:
          CI: true

  deploy-app:
    name: DeployApp
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 16
      - name: Make artifact directory
        run: mkdir out
      - name: Download Artifact
        uses: actions/download-artifact@main
        with:
          name: out
          path: ./out
      - name: Display structure of downloaded files
        run: ls -R
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy-functions:
    name: DeployFunctions
    needs: build-functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 16
      - name: npm install
        working-directory: ./functions
        run: |
          npm ci
        env:
          CI: true
      - name: set config
        uses: w9jds/firebase-action@master
        with:
          args: functions:config:set gmail.email=$FIREBASE_CONFIG_GMAIL_ADDRESS gmail.password=$FIREBASE_CONFIG_GMAIL_PASSWORD admin.email=$FIREBASE_CONFIG_ADMIN_ADDRESS
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_CONFIG_GMAIL_ADDRESS: ${{ secrets.FIREBASE_CONFIG_GMAIL_ADDRESS }}
          FIREBASE_CONFIG_GMAIL_PASSWORD: ${{ secrets.FIREBASE_CONFIG_GMAIL_PASSWORD }}
          FIREBASE_CONFIG_ADMIN_ADDRESS: ${{ secrets.FIREBASE_CONFIG_ADMIN_ADDRESS }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
