name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-app:
    name: BuildApp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 10
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build
          npm run lint
        env:
          CI: true

  build-functions:
    name: BuildFunctions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 10
      - name: npm install, build, and test
        run: |
          cd functions
          npm ci
          npm run lint
        env:
          CI: true

  deploy:
    name: Deploy
    needs: [build-app, build-functions]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 10
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
